# Generated by Django 4.2.27 on 2026-01-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='archivo_video',
            field=models.CharField(default='video1.txt', help_text='Nombre del archivo .txt del video (ej: video1.txt)', max_length=100),
        ),
    ]
